set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  MULTICHARGE_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  MULTICHARGE_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)
set(
  MULTICHARGE_DEPENDENCIES
  "$<$<BOOL:${MULTICHARGE_USE_MCTCLIB}>:mctc-lib::mctc-lib>"
  "$<$<BOOL:${MULTICHARGE_WITH_OpenMP}>:OpenMP::OpenMP_Fortran>"
  "LAPACK::LAPACK"
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${MULTICHARGE_LIBRARIES} ${MULTICHARGE_DEPENDENCIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${MULTICHARGE_INCLUDEDIRS})
